### ISSUE TITLE
Add support for cloudEvents

### ISSUE THREAD

**Issue by chris-aeviator** [batchcorp/plumber#338] opened 2023-02-26 11:12 UTC
**What would you like to see added?**
Cloudevents (https://cloudevents.io/) is a specification for describing event data in a common way. Cloud events are used in a variety of application platforms and are independent of the underlying transport layer, so plumber would be the ideal tool to send them from a terminal.

**Use Case**

When developing a service that expects cloudevents structured messages, plumber would act as the swiss army knife for sending them in an easy way.

Supported adapters are e.g. 

- kafka
- mqtt
- NATS
- AMQP

more at https://github.com/cloudevents/spec#cloudevents-documents

**Proposed Change**

add a CLI flag `--cloudEvent` that turns `--input {"data": {"userSignedUpEvent": ...}` into a cloudEvent

**Who Benefits from the Change(s)?**

All users working with the serverlessworkflow.io specification and cloudEvent users in general.

**Additional context**
example of a cloud event message
```
{
  "data":{ EVENT_DATA

 }
  "datacontenttype": "application/json; charset=utf-8",
  "id": "MESSAGE_ID

",
  "source": "//cloudaudit.googleapis.com/projects/PROJECT_ID

/logs/data_access",
  "specversion": "1.0",
  "type": "google.cloud.audit.log.v1.written",
  "time": "EVENT_GENERATION_TIME

",
  "dataschema": "https://googleapis.github.io/google-cloudevents/jsonschema/google/events/cloud/audit/v1/LogEntryData.json",
  "methodName": "jobservice.jobcompleted",
  "resourceName": "projects/my-project/jobs/bqjob_r3ac45813612fa2d6_0000017d591922c9_1",
  "serviceName": "bigquery.googleapis.com",
  "subject": "bigquery.googleapis.com/projects/my-project/jobs/bqjob_r3ac45813612fa2d6_0000017d591922c9_1",
}
```

sample python code to construct a cloud event

```
import datetime
import json
import uuid

event = {}
event['id'] = str(uuid.uuid4())
event['source'] = 'my-event-source'
event[type] = 'my-event-type'
event['specversion'] = '0.3'
event['time'] = datetime.datetime.utcnow().isoformat('T') + 'Z'
event['data'] = 'Hello World!'
event_json_str = json.dumps(event)

# Alternatively with Cloud Events SDK
from cloudevents.sdk.event import v03

event = (
	v03.Event().
	SetEventID('my-event-id').
	SetSource('my-event-source').
	SetEventType('my-event-type').
	SetEventTime(datetime.datetime.utcnow().isoformat('T') + 'Z').
	SetData('Hello World!')
```

**Comment by blinktag** [comment] 2023-03-06 18:34
Thanks for the suggestion! We are working on getting this added to Plumber this week

**Comment by blinktag** [comment] 2023-03-09 00:27
@chris-aeviator I'm trying to gauge how people might typically use this. Would the use-case just be a single flag, which unmarshals the JSON into a cloud event, and then uses the SDK's libs to ship the message correctly? Or would it also need flags for all the message options such as `--id`, `--subject`, `--data-schema`, etc?

Also is there any functionality you are looking for on reads? Currently plumber exposes the message bus' headers and metadata, which should by default include the `ce_*` attributes

**Comment by blinktag** [comment] 2023-04-10 14:03
Hi @chris-aeviator, can you check my previous reply. I want to make sure I grokked the intended behavior before releasing this. Thank you!

**Comment by chris-aeviator** [comment] 2023-04-10 15:20
Sorry for the late reply - most fields are standardized (so the flag logic would be appropriate) but there’s also the possibility to add custom fields - for a standard use case this is optional though

**Comment by blinktag** [comment] 2023-04-14 17:37
@chris-aeviator Cloudevents support has landed in https://github.com/batchcorp/plumber/releases/tag/v2.3.0
It is currently supported for Kafka, NATS, NATS streaming, and NATS jetstream. Example usage is here:
https://github.com/batchcorp/plumber/blob/master/docs/examples.md#publish-cloudevents

Let me know if you have any issues with the functionality

**Closed by blinktag** 2023-04-14 17:37 UTC
